import Link from "next/link";

import { ContentPiece } from "@/lib/types";
import { ReviewStateBadge } from "@/components/review-state-badge";

export function ContentPieceQueue({
  campaignId,
  pieces,
}: {
  campaignId: string;
  pieces: ContentPiece[];
}) {
  return (
    <section className="content-list-card">
      <div className="content-list-card-header">
        <h3>Content Pieces</h3>
        <div className="content-list-card-actions">
          <button type="button" className="content-list-icon-button" aria-label="Filter content">
            ≡
          </button>
          <button type="button" className="content-list-icon-button" aria-label="More options">
            ⋮
          </button>
        </div>
      </div>
      <div className="queue-list content-piece-list">
        {pieces.map((piece) => (
          <Link
            key={piece.id}
            href={`/campaigns/${campaignId}/content-pieces/${piece.id}`}
            className="content-piece-row"
          >
            <div className="content-piece-row-copy">
              <div>
                <div className="content-piece-row-meta">
                  <span className="content-piece-kind">Content Piece</span>
                  <span className="content-piece-timestamp">
                    {piece.latest_reviewable_suggestion ? "Generated by AI" : "Just created"}
                  </span>
                </div>
                <h4>{piece.current_text.slice(0, 96) || "Empty text snippet..."}</h4>
              </div>
              <p className="content-piece-row-preview">
                {piece.latest_metadata
                  ? `"Metadata available for this piece."`
                  : `"Open to edit canonical text, generate drafts, or translate."`}
              </p>
            </div>
            <div className="content-piece-row-status">
              <ReviewStateBadge state={piece.review_state} />
              <span className="content-piece-chevron">›</span>
            </div>
          </Link>
        ))}
      </div>
      <div className="content-list-footer">
        <button type="button">Load More Pieces</button>
      </div>
    </section>
  );
}
