import { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { contentApi, aiApi } from '../lib/api';
import { StatusBadge } from '../components/StatusBadge';
import { ReviewActions } from '../components/ReviewActions';
import { AiToolbar } from '../components/AiToolbar';
import { ModelComparison } from '../components/ModelComparison';
import { MetadataPanel } from '../components/MetadataPanel';
import { TranslationsList } from '../components/TranslationsList';
import type { ContentStatus, CompareResponse } from '../lib/types';

export default function ContentDetail() {
  const { id } = useParams<{ id: string }>();
  const queryClient = useQueryClient();
  const [selectedModel, setSelectedModel] = useState<string | undefined>();
  const [editBody, setEditBody] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [reviewNotes, setReviewNotes] = useState('');
  const [comparison, setComparison] = useState<CompareResponse | null>(null);
  const [translateLang, setTranslateLang] = useState('');

  const { data: piece, isLoading } = useQuery({
    queryKey: ['content', id],
    queryFn: () => contentApi.get(id!),
    enabled: !!id,
  });

  const { data: providers } = useQuery({
    queryKey: ['providers'],
    queryFn: aiApi.providers,
  });

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['content', id] });
    queryClient.invalidateQueries({ queryKey: ['campaigns'] });
  };

  const generateMut = useMutation({
    mutationFn: () => aiApi.generate(id!, selectedModel),
    onSuccess: invalidate,
  });

  const translateMut = useMutation({
    mutationFn: () => aiApi.translate(id!, translateLang, selectedModel),
    onSuccess: () => {
      invalidate();
      setTranslateLang('');
    },
  });

  const extractMut = useMutation({
    mutationFn: () => aiApi.extract(id!, selectedModel),
    onSuccess: invalidate,
  });

  const chainMut = useMutation({
    mutationFn: () => aiApi.chain(id!, selectedModel),
    onSuccess: () => {
      invalidate();
    },
  });

  const compareMut = useMutation({
    mutationFn: () => aiApi.compare(id!),
    onSuccess: (data: CompareResponse) => setComparison(data),
  });

  const statusMut = useMutation({
    mutationFn: ({ status, notes }: { status: ContentStatus; notes?: string }) =>
      contentApi.updateStatus(id!, { status, reviewNotes: notes }),
    onSuccess: invalidate,
  });

  const updateMut = useMutation({
    mutationFn: () =>
      contentApi.update(id!, { body: editBody, reviewNotes: reviewNotes || undefined }),
    onSuccess: () => {
      invalidate();
      setIsEditing(false);
    },
  });

  const isAiLoading =
    generateMut.isPending ||
    translateMut.isPending ||
    extractMut.isPending ||
    chainMut.isPending ||
    compareMut.isPending;

  const aiError =
    generateMut.error ?? translateMut.error ?? extractMut.error ?? chainMut.error ?? compareMut.error ?? null;

  if (isLoading) return <div className="p-8 text-center">Loading...</div>;
  if (!piece) return <div className="p-8 text-center">Content not found</div>;

  const availableLangs =
    piece.campaign?.targetLanguages.filter(
      (l) =>
        l !== piece.language &&
        !piece.translations?.some((t) => t.language === l),
    ) ?? [];

  return (
    <div className="max-w-5xl mx-auto p-6">
      <Link
        to={`/campaigns/${piece.campaignId}`}
        className="text-zinc-500 hover:text-zinc-900 transition-colors text-sm mb-8 inline-flex items-center gap-2 font-medium"
      >
        ← Back to Campaign
      </Link>

      {/* Header */}
      <div className="card p-6 mb-6">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-zinc-900">{piece.title}</h1>
            <div className="flex gap-2 mt-2 items-center text-[11px] font-medium text-zinc-500 uppercase tracking-wider">
              <span>{piece.type.replace('_', ' ')}</span>
              <span className="text-zinc-300">•</span>
              <span>{piece.language}</span>
              {piece.aiModel && (
                <>
                  <span className="text-zinc-300">•</span>
                  <span className="text-purple-600 bg-purple-50 px-2.5 py-1 rounded-full border border-purple-100">
                    Generated by {piece.aiModel}
                  </span>
                </>
              )}
            </div>
          </div>
          <StatusBadge status={piece.status} />
        </div>
      </div>

      {/* Content Body */}
      <div className="card p-6 mb-6">
        <h2 className="text-lg font-semibold text-zinc-900 mb-4">Content</h2>
        {isEditing ? (
          <div className="space-y-4">
            <textarea
              value={editBody}
              onChange={(e) => setEditBody(e.target.value)}
              className="input-field min-h-[200px] font-mono whitespace-pre-wrap leading-relaxed"
              maxLength={10000}
            />
            <textarea
              value={reviewNotes}
              onChange={(e) => setReviewNotes(e.target.value)}
              placeholder="Review notes (optional)"
              className="input-field"
              rows={2}
              maxLength={5000}
            />
            <div className="flex gap-2 pt-2">
              <button
                onClick={() => updateMut.mutate()}
                disabled={updateMut.isPending}
                className="btn-primary"
              >
                Save Changes
              </button>
              <button
                onClick={() => setIsEditing(false)}
                className="btn-secondary"
              >
                Cancel
              </button>
            </div>
          </div>
        ) : (
          <div>
            {piece.body ? (
              <p className="whitespace-pre-wrap text-zinc-800 leading-relaxed text-[15px]">{piece.body}</p>
            ) : (
              <div className="bg-zinc-50 border border-dashed border-zinc-200 rounded-md p-8 text-center bg-zinc-50/50">
                <p className="text-zinc-500 text-sm">
                  No content yet. Generate a draft using AI below.
                </p>
              </div>
            )}
            {piece.body && (
              <button
                onClick={() => {
                  setEditBody(piece.body);
                  setReviewNotes(piece.reviewNotes ?? '');
                  setIsEditing(true);
                }}
                className="mt-6 text-sm font-medium text-zinc-600 hover:text-zinc-900 underline-offset-4 hover:underline transition-colors"
              >
                Edit content manually
              </button>
            )}
          </div>
        )}
      </div>

      <ReviewActions
        status={piece.status}
        body={piece.body}
        reviewNotes={piece.reviewNotes}
        isPending={statusMut.isPending}
        error={statusMut.error}
        onChangeStatus={(status, notes) => statusMut.mutate({ status, notes })}
      />

      <AiToolbar
        selectedModel={selectedModel}
        onModelChange={setSelectedModel}
        providers={providers}
        hasBody={!!piece.body}
        availableLangs={availableLangs}
        translateLang={translateLang}
        onTranslateLangChange={setTranslateLang}
        isAiLoading={isAiLoading}
        onGenerate={() => generateMut.mutate()}
        onExtract={() => extractMut.mutate()}
        onChain={() => chainMut.mutate()}
        onCompare={() => compareMut.mutate()}
        onTranslate={() => translateMut.mutate()}
        generating={generateMut.isPending}
        extracting={extractMut.isPending}
        chaining={chainMut.isPending}
        comparing={compareMut.isPending}
        translating={translateMut.isPending}
        error={aiError}
      />

      {comparison && <ModelComparison comparison={comparison} />}

      {piece.metadata && (
        <MetadataPanel metadata={piece.metadata as unknown as Record<string, unknown>} />
      )}

      {piece.translations && piece.translations.length > 0 && (
        <TranslationsList translations={piece.translations} />
      )}
    </div>
  );
}
