import { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { contentApi, aiApi } from '../lib/api';
import { StatusBadge } from '../components/StatusBadge';
import type { ContentStatus, CompareResponse } from '../lib/types';

export default function ContentDetail() {
  const { id } = useParams<{ id: string }>();
  const queryClient = useQueryClient();
  const [selectedModel, setSelectedModel] = useState<string | undefined>();
  const [editBody, setEditBody] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [reviewNotes, setReviewNotes] = useState('');
  const [comparison, setComparison] = useState<CompareResponse | null>(null);
  const [translateLang, setTranslateLang] = useState('');

  const { data: piece, isLoading } = useQuery({
    queryKey: ['content', id],
    queryFn: () => contentApi.get(id!),
    enabled: !!id,
  });

  const { data: providers } = useQuery({
    queryKey: ['providers'],
    queryFn: aiApi.providers,
  });

  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['content', id] });
    queryClient.invalidateQueries({ queryKey: ['campaigns'] });
  };

  const generateMut = useMutation({
    mutationFn: () => aiApi.generate(id!, selectedModel),
    onSuccess: invalidate,
  });

  const translateMut = useMutation({
    mutationFn: () => aiApi.translate(id!, translateLang, selectedModel),
    onSuccess: () => {
      invalidate();
      setTranslateLang('');
    },
  });

  const extractMut = useMutation({
    mutationFn: () => aiApi.extract(id!, selectedModel),
    onSuccess: invalidate,
  });

  const chainMut = useMutation({
    mutationFn: () => aiApi.chain(id!, selectedModel),
    onSuccess: () => {
      invalidate();
    },
  });

  const compareMut = useMutation({
    mutationFn: () => aiApi.compare(id!),
    onSuccess: (data: CompareResponse) => setComparison(data),
  });

  const statusMut = useMutation({
    mutationFn: ({ status, notes }: { status: ContentStatus; notes?: string }) =>
      contentApi.updateStatus(id!, { status, reviewNotes: notes }),
    onSuccess: invalidate,
  });

  const updateMut = useMutation({
    mutationFn: () =>
      contentApi.update(id!, { body: editBody, reviewNotes: reviewNotes || undefined }),
    onSuccess: () => {
      invalidate();
      setIsEditing(false);
    },
  });

  const isAiLoading =
    generateMut.isPending ||
    translateMut.isPending ||
    extractMut.isPending ||
    chainMut.isPending ||
    compareMut.isPending;

  if (isLoading) return <div className="p-8 text-center">Loading...</div>;
  if (!piece) return <div className="p-8 text-center">Content not found</div>;

  const availableLangs =
    piece.campaign?.targetLanguages.filter(
      (l) =>
        l !== piece.language &&
        !piece.translations?.some((t) => t.language === l),
    ) ?? [];

  return (
    <div className="max-w-5xl mx-auto p-6">
      <Link
        to={`/campaigns/${piece.campaignId}`}
        className="text-blue-600 hover:underline text-sm mb-4 inline-block"
      >
        ← Back to Campaign
      </Link>

      {/* Header */}
      <div className="bg-white rounded-lg shadow p-5 mb-4">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-xl font-bold">{piece.title}</h1>
            <div className="flex gap-2 mt-1 items-center text-sm text-gray-500">
              <span>{piece.type.replace('_', ' ')}</span>
              <span>•</span>
              <span>{piece.language}</span>
              {piece.aiModel && (
                <>
                  <span>•</span>
                  <span className="text-purple-600">Generated by {piece.aiModel}</span>
                </>
              )}
            </div>
          </div>
          <StatusBadge status={piece.status} />
        </div>
      </div>

      {/* Content Body */}
      <div className="bg-white rounded-lg shadow p-5 mb-4">
        <h2 className="font-semibold mb-2">Content</h2>
        {isEditing ? (
          <div className="space-y-3">
            <textarea
              value={editBody}
              onChange={(e) => setEditBody(e.target.value)}
              className="w-full border rounded px-3 py-2 min-h-[150px] font-mono text-sm"
              maxLength={10000}
            />
            <textarea
              value={reviewNotes}
              onChange={(e) => setReviewNotes(e.target.value)}
              placeholder="Review notes (optional)"
              className="w-full border rounded px-3 py-2"
              rows={2}
              maxLength={5000}
            />
            <div className="flex gap-2">
              <button
                onClick={() => updateMut.mutate()}
                disabled={updateMut.isPending}
                className="bg-green-600 text-white px-3 py-1.5 rounded text-sm hover:bg-green-700 disabled:opacity-50"
              >
                Save Changes
              </button>
              <button
                onClick={() => setIsEditing(false)}
                className="bg-gray-200 px-3 py-1.5 rounded text-sm hover:bg-gray-300"
              >
                Cancel
              </button>
            </div>
          </div>
        ) : (
          <div>
            {piece.body ? (
              <p className="whitespace-pre-wrap text-gray-700">{piece.body}</p>
            ) : (
              <p className="text-gray-400 italic">
                No content yet. Generate a draft using AI below.
              </p>
            )}
            {piece.body && (
              <button
                onClick={() => {
                  setEditBody(piece.body);
                  setReviewNotes(piece.reviewNotes ?? '');
                  setIsEditing(true);
                }}
                className="mt-3 text-blue-600 text-sm hover:underline"
              >
                Edit content
              </button>
            )}
          </div>
        )}
      </div>

      {/* Review Actions */}
      <div className="bg-white rounded-lg shadow p-5 mb-4">
        <h2 className="font-semibold mb-3">Review Actions</h2>
        {piece.reviewNotes && (
          <p className="text-sm text-gray-500 mb-3 bg-gray-50 p-2 rounded">
            <strong>Notes:</strong> {piece.reviewNotes}
          </p>
        )}
        <div className="flex gap-2 flex-wrap">
          {piece.status === 'AI_SUGGESTED' && (
            <>
              <button
                onClick={() => statusMut.mutate({ status: 'APPROVED' })}
                disabled={statusMut.isPending}
                className="bg-green-600 text-white px-3 py-1.5 rounded text-sm hover:bg-green-700 disabled:opacity-50"
              >
                Approve
              </button>
              <button
                onClick={() => statusMut.mutate({ status: 'REVIEWED' })}
                disabled={statusMut.isPending}
                className="bg-yellow-500 text-white px-3 py-1.5 rounded text-sm hover:bg-yellow-600 disabled:opacity-50"
              >
                Mark as Reviewed
              </button>
              <button
                onClick={() => statusMut.mutate({ status: 'REJECTED', notes: reviewNotes || undefined })}
                disabled={statusMut.isPending}
                className="bg-red-600 text-white px-3 py-1.5 rounded text-sm hover:bg-red-700 disabled:opacity-50"
              >
                Reject
              </button>
            </>
          )}
          {piece.status === 'REVIEWED' && (
            <>
              <button
                onClick={() => statusMut.mutate({ status: 'APPROVED' })}
                disabled={statusMut.isPending}
                className="bg-green-600 text-white px-3 py-1.5 rounded text-sm hover:bg-green-700 disabled:opacity-50"
              >
                Approve
              </button>
              <button
                onClick={() => statusMut.mutate({ status: 'REJECTED' })}
                disabled={statusMut.isPending}
                className="bg-red-600 text-white px-3 py-1.5 rounded text-sm hover:bg-red-700 disabled:opacity-50"
              >
                Reject
              </button>
            </>
          )}
          {piece.status === 'REJECTED' && (
            <button
              onClick={() => statusMut.mutate({ status: 'DRAFT' })}
              disabled={statusMut.isPending}
              className="bg-gray-600 text-white px-3 py-1.5 rounded text-sm hover:bg-gray-700 disabled:opacity-50"
            >
              Reset to Draft
            </button>
          )}
          {(piece.status === 'APPROVED' || piece.status === 'DRAFT') &&
            piece.status === 'APPROVED' && (
              <p className="text-green-600 text-sm">✓ This content is approved.</p>
            )}
          {piece.status === 'DRAFT' && !piece.body && (
            <p className="text-gray-400 text-sm">Generate a draft first to enable review actions.</p>
          )}
        </div>
        {statusMut.isError && (
          <p className="text-red-600 text-sm mt-2">{statusMut.error.message}</p>
        )}
      </div>

      {/* AI Controls */}
      <div className="bg-white rounded-lg shadow p-5 mb-4">
        <h2 className="font-semibold mb-3">AI Tools</h2>
        <div className="flex items-center gap-3 mb-3">
          <label className="text-sm text-gray-500">Model:</label>
          <select
            value={selectedModel ?? ''}
            onChange={(e) =>
              setSelectedModel(e.target.value || undefined)
            }
            className="border rounded px-2 py-1 text-sm"
          >
            <option value="">Default ({providers?.default})</option>
            {providers?.available.map((p) => (
              <option key={p} value={p}>
                {p}
              </option>
            ))}
          </select>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={() => generateMut.mutate()}
            disabled={isAiLoading}
            className="bg-purple-600 text-white px-3 py-1.5 rounded text-sm hover:bg-purple-700 disabled:opacity-50"
          >
            {generateMut.isPending ? 'Generating...' : 'Generate Draft'}
          </button>
          <button
            onClick={() => extractMut.mutate()}
            disabled={isAiLoading || !piece.body}
            className="bg-indigo-600 text-white px-3 py-1.5 rounded text-sm hover:bg-indigo-700 disabled:opacity-50"
          >
            {extractMut.isPending ? 'Extracting...' : 'Extract Metadata'}
          </button>
          <button
            onClick={() => chainMut.mutate()}
            disabled={isAiLoading}
            className="bg-gradient-to-r from-purple-600 to-indigo-600 text-white px-3 py-1.5 rounded text-sm hover:from-purple-700 hover:to-indigo-700 disabled:opacity-50"
          >
            {chainMut.isPending
              ? 'Running pipeline...'
              : 'Full Pipeline (Generate → Translate → Extract)'}
          </button>
          <button
            onClick={() => compareMut.mutate()}
            disabled={isAiLoading || (providers?.available.length ?? 0) < 2}
            className="bg-amber-600 text-white px-3 py-1.5 rounded text-sm hover:bg-amber-700 disabled:opacity-50"
            title={
              (providers?.available.length ?? 0) < 2
                ? 'Need 2+ providers for comparison'
                : undefined
            }
          >
            {compareMut.isPending ? 'Comparing...' : 'Compare Models'}
          </button>
        </div>

        {/* Translate */}
        {availableLangs.length > 0 && (
          <div className="flex items-center gap-2 mt-3">
            <select
              value={translateLang}
              onChange={(e) => setTranslateLang(e.target.value)}
              className="border rounded px-2 py-1 text-sm"
            >
              <option value="">Translate to...</option>
              {availableLangs.map((l) => (
                <option key={l} value={l}>
                  {l}
                </option>
              ))}
            </select>
            <button
              onClick={() => translateMut.mutate()}
              disabled={isAiLoading || !translateLang || !piece.body}
              className="bg-teal-600 text-white px-3 py-1.5 rounded text-sm hover:bg-teal-700 disabled:opacity-50"
            >
              {translateMut.isPending ? 'Translating...' : 'Translate'}
            </button>
          </div>
        )}

        {/* AI errors */}
        {(generateMut.isError ||
          translateMut.isError ||
          extractMut.isError ||
          chainMut.isError ||
          compareMut.isError) && (
          <p className="text-red-600 text-sm mt-2">
            {(generateMut.error ?? translateMut.error ?? extractMut.error ?? chainMut.error ?? compareMut.error)?.message}
          </p>
        )}
      </div>

      {/* Comparison Results */}
      {comparison && (
        <div className="bg-white rounded-lg shadow p-5 mb-4">
          <h2 className="font-semibold mb-3">Model Comparison</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {Object.entries(comparison.comparisons).map(([provider, body]) => (
              <div key={provider} className="border rounded p-3">
                <h3 className="text-sm font-medium text-purple-600 mb-2">
                  {provider}
                </h3>
                <p className="text-sm text-gray-700 whitespace-pre-wrap">{body}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Metadata */}
      {piece.metadata && (
        <div className="bg-white rounded-lg shadow p-5 mb-4">
          <h2 className="font-semibold mb-3">Metadata</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
            <div>
              <span className="text-gray-500">Tone:</span>
              <p className="font-medium capitalize">{(piece.metadata as any).tone}</p>
            </div>
            <div>
              <span className="text-gray-500">Sentiment:</span>
              <p className="font-medium capitalize">{(piece.metadata as any).sentiment}</p>
            </div>
            <div>
              <span className="text-gray-500">Readability:</span>
              <p className="font-medium capitalize">{(piece.metadata as any).readability}</p>
            </div>
            <div>
              <span className="text-gray-500">Keywords:</span>
              <div className="flex flex-wrap gap-1 mt-1">
                {((piece.metadata as any).keywords ?? []).map((kw: string) => (
                  <span
                    key={kw}
                    className="bg-blue-50 text-blue-600 px-1.5 py-0.5 rounded text-xs"
                  >
                    {kw}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Translations */}
      {piece.translations && piece.translations.length > 0 && (
        <div className="bg-white rounded-lg shadow p-5 mb-4">
          <h2 className="font-semibold mb-3">Translations</h2>
          <div className="space-y-3">
            {piece.translations.map((t) => (
              <Link
                key={t.id}
                to={`/content/${t.id}`}
                className="block border rounded p-3 hover:bg-gray-50 transition"
              >
                <div className="flex items-center justify-between">
                  <div>
                    <span className="bg-gray-100 text-gray-600 px-2 py-0.5 rounded text-xs mr-2">
                      {t.language}
                    </span>
                    <span className="font-medium text-sm">{t.title}</span>
                  </div>
                  <StatusBadge status={t.status} />
                </div>
                {t.body && (
                  <p className="text-sm text-gray-500 mt-1 line-clamp-2">{t.body}</p>
                )}
              </Link>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
